export type GalleryImage = {
  alt: string
  src: string
}

/**
 * The complete public gallery published on hsmaries.space, preserved in the
 * same newest-first order. The ERC 2026 finals set from Kraków leads the list:
 * the first six entries feed the homepage rail, the rest of the curated finals
 * photos follow, then the historical photo archive (renders and diagrams were
 * retired once the rover had competed). CMS media is merged over this archive
 * at runtime.
 */
export const authoritativeGalleryImages: GalleryImage[] = [
  { alt: 'LEAP-One\'s wheels dig into the sand during the test, with the sponsor and flag decals on its flank.', src: '/media/erc-2026-finals-07-wheels-in-the-sand.jpg' },
  { alt: 'The crew huddles around the control-station monitor in the pit tent, the table draped in the Thuringian and German flags.', src: '/media/erc-2026-finals-10-control-station-pit-tent.jpg' },
  { alt: 'The team lines up on the steps with the German flag, LEAP-One carrying the quadcopter in front.', src: '/media/erc-2026-finals-34-team-on-the-steps.jpg' },
  { alt: 'The LEAPONE competition plate is held up against the rocky Mars yard.', src: '/media/erc-2026-finals-28-leapone-plate-mars-yard.jpg' },
  { alt: 'The team poses with the Japanese team, both flags side by side and LEAP-One behind them.', src: '/media/erc-2026-finals-37-with-the-japanese-team.jpg' },
  { alt: 'The sunset is reflected in the glass facade above the ERC team-zone entrance at AGH.', src: '/media/erc-2026-finals-39-agh-team-zone-sunset.jpg' },
  { alt: 'LEAP-One stands on the campus plaza with its flag and sponsor decals.', src: '/media/erc-2026-finals-01-campus-plaza-before-departure.jpg' },
  { alt: 'The ERC 2026 banner on the AGH fence announces the event dates in Kraków.', src: '/media/erc-2026-finals-02-agh-banner.jpg' },
  { alt: 'Morning light falls on the Mars yard, the ERC banner and the blue pit tents before the first runs.', src: '/media/erc-2026-finals-03-mars-yard-morning.jpg' },
  { alt: 'A team member fastens the suspension of the bare LEAP-One chassis on the pavement with a hex key set beside it.', src: '/media/erc-2026-finals-04-chassis-rebuild-suspension.jpg' },
  { alt: 'The rebuild continues on the grass with the tool kit and spare wheels laid out around the chassis.', src: '/media/erc-2026-finals-05-chassis-rebuild-wiring.jpg' },
  { alt: 'Team members crouch beside LEAP-One as it drives onto the sand of the Mars yard for a test run.', src: '/media/erc-2026-finals-06-first-sand-test.jpg' },
  { alt: 'Another team runs its rover on the gravel mounds of the Mars yard with the AGH campus behind.', src: '/media/erc-2026-finals-08-mars-yard-other-team-run.jpg' },
  { alt: 'Two team members lean over a laptop beside LEAP-One\'s mast in the indoor hall.', src: '/media/erc-2026-finals-09-laptop-check-indoor-hall.jpg' },
  { alt: 'A team member works at a laptop under the pit tent with the arena netting behind.', src: '/media/erc-2026-finals-11-pit-tent-laptop.jpg' },
  { alt: 'Team members repair wiring beside LEAP-One\'s arm and signal tower with a toolbox open on the grass.', src: '/media/erc-2026-finals-12-field-wiring-repair.jpg' },
  { alt: 'One team member sets the arm while another sorts tools on the lawn before a run.', src: '/media/erc-2026-finals-13-arm-setup-on-the-lawn.jpg' },
  { alt: 'Three team members walk LEAP-One out to the field with the controller in hand.', src: '/media/erc-2026-finals-14-walking-leap-one-to-the-field.jpg' },
  { alt: 'LEAP-One crosses the sand and rock of the Mars yard with its arm raised and a marker on its mast.', src: '/media/erc-2026-finals-15-leap-one-mars-yard-arm-raised.jpg' },
  { alt: 'A team member kneels beside LEAP-One with sample containers mounted and the arm raised.', src: '/media/erc-2026-finals-16-sample-containers-arm-raised.jpg' },
  { alt: 'LEAP-One climbs the rocky slope with its suspension articulating over the stones.', src: '/media/erc-2026-finals-17-leap-one-climbs-rocky-slope.jpg' },
  { alt: 'LEAP-One extends its arm on the Mars yard in front of the solar-panel stand and the red ERC dome.', src: '/media/erc-2026-finals-18-arm-extended-solar-stand.jpg' },
  { alt: 'LEAP-One faces the camera on the gravel with its arm extended and a sample container on top.', src: '/media/erc-2026-finals-19-leap-one-gravel-arm-extended.jpg' },
  { alt: 'LEAP-One reaches its arm toward the ERC maintenance panel beside marker 14.', src: '/media/erc-2026-finals-20-maintenance-panel-marker-14.jpg' },
  { alt: 'The gripper operates the switches on the maintenance panel.', src: '/media/erc-2026-finals-21-gripper-on-maintenance-panel.jpg' },
  { alt: 'On the rain day LEAP-One works the rocky terrain under an umbrella with its arm wrapped in protective plastic.', src: '/media/erc-2026-finals-22-rain-day-umbrella.jpg' },
  { alt: 'LEAP-One carries the quadcopter on its top deck beside marker 9.', src: '/media/erc-2026-finals-23-carrying-the-quadcopter.jpg' },
  { alt: 'A low angle shows LEAP-One\'s sponsor panel, German flag and LEAPONE plate above the chevron wheels.', src: '/media/erc-2026-finals-24-sponsor-panel-low-angle.jpg' },
  { alt: 'The gripper, depth camera and emergency stop sit above the sponsor logos on LEAP-One\'s front.', src: '/media/erc-2026-finals-25-gripper-depth-camera-front.jpg' },
  { alt: 'LEAP-One\'s arm, sensor mast and sample container in front of the ERC banner.', src: '/media/erc-2026-finals-26-arm-mast-erc-banner.jpg' },
  { alt: 'LEAP-One raises its arm on the grass beneath the blue ERC welcome banner.', src: '/media/erc-2026-finals-27-arm-raised-welcome-banner.jpg' },
  { alt: 'The team\'s quadcopter rests on its cardboard landing pad with a fiducial marker on the grass.', src: '/media/erc-2026-finals-29-quadcopter-landing-pad.jpg' },
  { alt: 'The carbon quadcopter sits on its printed marker sheet seen from above.', src: '/media/erc-2026-finals-30-quadcopter-marker-sheet.jpg' },
  { alt: 'A team member presents LEAP-One\'s mobility results during the team presentation in the lecture hall.', src: '/media/erc-2026-finals-31-presentation-lecture-hall.jpg' },
  { alt: 'The team lines up under the projector screen after the presentation.', src: '/media/erc-2026-finals-32-team-after-presentation.jpg' },
  { alt: 'The team gathers around LEAP-One on the Mars yard with the German and Thuringian flags.', src: '/media/erc-2026-finals-33-team-with-leap-one-and-flags.jpg' },
  { alt: 'The team gathers around LEAP-One under the AGH faculty lettering at the host university.', src: '/media/erc-2026-finals-35-team-at-agh.jpg' },
  { alt: 'Three team members stand behind LEAP-One with the quadcopter in hand.', src: '/media/erc-2026-finals-36-three-members-with-quadcopter.jpg' },
  { alt: 'Several teams gather with their rovers and drones under Indian and German flags.', src: '/media/erc-2026-finals-38-teams-with-rovers-and-drones.jpg' },
  { alt: 'LEAP-One picks its way across the rocks of the Mars yard beside marker 9, with the crowd and the ERC flag behind.', src: '/media/erc-2026-finals-40-rover-on-the-rocks.jpg' },
  { alt: 'LEAP-One climbs the gravel with the team’s quadcopter riding on its deck.', src: '/media/erc-2026-finals-41-quadcopter-on-deck.jpg' },
  { alt: 'LEAP-One’s rocker-bogie suspension works over the loose rock of the Mars yard.', src: '/media/erc-2026-finals-42-suspension-over-the-rocks.jpg' },
  { alt: 'LEAP-One carries the quadcopter past the navigation markers on the Mars yard.', src: '/media/erc-2026-finals-43-carrying-the-quadcopter-past-the-markers.jpg' },
  { alt: 'HSM Aries presenting LEAP-One at Space Night 2026', src: '/media/DSC02769-scaled.jpg' },
  { alt: 'HSM Aries crew and guests at Space Night 2026', src: '/media/DSC02608-scaled.jpg' },
  { alt: 'LEAP-One on display at Space Night 2026', src: '/media/DSC02577-scaled.jpg' },
  { alt: 'HSM Aries team with Thuringian state leadership', src: '/media/1777480994040.jpg' },
  { alt: 'Space Night 2026 aerospace exhibition', src: '/media/DSC02822-scaled.jpg' },
  { alt: 'LEAP-One rover during multi-terrain trials', src: '/media/WhatsApp-Image-2026-05-10-at-19.49.07.jpeg' },
  { alt: 'KUKA Robotics visit to Hochschule Schmalkalden', src: '/media/1769862721077.jpg' },
  { alt: 'The Red Planet Awaits — HSM Aries rover programme', src: '/media/IMG_2006.JPG-1-scaled.jpeg' },
  { alt: 'AQUILA drone developed alongside the rover programme', src: '/media/IMG_1913.JPG-scaled.jpeg' },
  { alt: 'Thuringia Minister of Science Christian Tischner visiting LEAP-One', src: '/media/WhatsApp-Image-2026-04-13-at-22.13.10.jpeg' },
  { alt: 'AQUILA drone field operations', src: '/media/IMG_1852.JPG-scaled.jpeg' },
  { alt: 'AQUILA drone assembly in the HSM Aries workshop', src: '/media/WhatsApp-Image-2026-05-10-at-19.49.02.jpeg' },
  { alt: 'LEAP-One first-phase completion team record', src: '/media/dsc01422-scaled.jpg' },
  { alt: 'LEAP-One CAN bus testing', src: '/media/img_8789-scaled.jpg' },
  { alt: 'Multiple ODrive controllers during CAN testing', src: '/media/img_8798-scaled.jpg' },
  { alt: 'Assembled LEAP-One rover chassis', src: '/media/sirleloimage.png' },
  { alt: 'Introductory briefing for new HSM Aries members', src: '/media/presentation-01.jpg' },
  { alt: 'New-member engineering programme briefing', src: '/media/presentation-01-03.jpg' },
  { alt: 'HSM Aries introductory team presentation', src: '/media/presentation-01-02.jpg' },
  { alt: 'HSM Aries presenting the rover programme at Boehm Group', src: '/media/pitching-in-boehm-scaled.jpg' },
  { alt: 'HSM Aries engineering team meeting', src: '/media/whatsapp-image-2025-03-26-at-4.01.37-pm-scaled.jpeg' },
  { alt: 'First HSM Aries team photo', src: '/media/hsm-aries-3.png' },
]
